config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :messages do
    collection do
      delete :destroyall
    end
  end


  root 'homes#home'

  get 'sessions/new' => 'sessions#new'
  post 'sessions/create' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  get 'users/new' => 'users#new'
  post 'users/create' => 'users#create'
  get 'users/search' => 'users#search'
  post 'users/search' => 'users#search_resp'
  get 'user/:id' => 'users#show'
  get 'user/:id/edit' => 'users#edit'
  patch 'user/:id/update' => 'users#update'
  get 'user/:id/delete' => 'users#delete'
  get 'user/:id/public' => 'users#show_public'

  post 'friendships/request' => 'friendships#request_friendship'
  post 'friendships/grant' => 'friendships#grant_friendship'
  get 'friendships/requests' => 'friendships#my_friendship_request'
  get 'friendships/grants' => 'friendships#my_friendship_grant'
  get 'friendships/finished' => 'friendships#finished_friendship_requests'

  get 'chats/bot' => 'chats#bot'
  post 'chats/bot_chat' => 'chats#bot_chat'
  resources :friendships
  resources :user
  resources :chats
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :messages, :dependent => :destroy
  def to_s
    "id:#{self.id} "\
      "name:#{self.name} description:#{self.description} "\
      "admin_id:#{self.admin_id} "\
      "created_at:#{self.created_at} updated_at:#{self.updated_at}"
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  include SessionsHelper
  include ChatsHelper
  respond_to :js, :html
  before_action :logged_in, except: [:bot_chat]
  before_action :set_chat, except: [:index, :new, :create, :bot , :bot_chat]
  before_action :correct_user, only: :show
  protect_from_forgery except: :bot_chat

  def index
    @friends=current_user.friends+current_user.inverse_friends
  end

  def add_user
    params[:users].each do |id|
      @chat.users<<User.find_by_id(id)
    end
    redirect_to chat_path(@chat), flash: {:info => "用户已成功拉入群聊"}
  end

  def delete_user
    user=User.find_by_id(params[:user_id])
    @chat.users.delete(user)
    redirect_to chat_path(@chat), flash: {:warning => "#{user.name}已成功退出群聊"}
  end

  def create
    user=User.find_by_id(params[:users])

    current_user.chats.each do |chat|
      if (chat.users-[user, current_user]).blank?
        redirect_to chat_path(chat) and return
      end
    end

    @chat = Chat.new
    @chat.users<<user
    @chat.users<<current_user
    @chat.admin_id=current_user.id
    @chat.name="#{user.name}-#{current_user.name}"

    if @chat.save
      redirect_to chat_path(@chat)
    else
      flash[:warning] = "错误,请重试"
      render chats_path, flash: flash
    end
  end

  def update
    if @chat.update_attributes(chat_params)
      flash= {success: "修改成功"}
    else
      flash= {danger: "修改失败，请重试"}
    end
    redirect_to chat_path(@chat), flash: flash
  end

  def trans_auth
    @chat.update_attribute(:admin_id, params[:admin_id])
    redirect_to chat_path(@chat), flash: {success: '移交成功！'}
  end

  def destroy
    @chat.destroy
    redirect_to chats_path, flash: {:danger => '聊天已删除'}
  end

  def show
    @new_message = Message.new
    @users_in_chat= @chat.users-[current_user]
    @friends=current_user.friends+current_user.inverse_friends
    @friends_out_chat=@friends-@chat.users
  end

  def bot
  end

  def bot_chat
    url = "http://openapi.tuling123.com/openapi/api/v2";
    apiKey = "3a189c6842524bb191f195b367a41b83";
    userId = "0";
    post_data = {
      "reqType":0,
      "perception": {
        "inputText": {
          "text": params[:text]
        },
      },
      "userInfo": {
        "apiKey": apiKey,
        "userId": userId
      }
    }
    uri = URI.parse(url)
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Post.new(uri.path, initheader = {'Content-Type' =>'application/json; charset=utf-8'})
    req.body = post_data.to_json
    res = JSON.parse(http.request(req).body)
    resp = {"response" => res["results"][0]["values"]["text"]}
    render json: resp
  end

  private

  def chat_params
    params.require(:chat).permit(:name, :description)
  end

  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def set_chat
    @chat=Chat.find_by_id(params[:id])
    if @chat.nil?
      redirect_to chats_path, flash: {:warning => "没有找到此次聊天的信息"}
    end
  end

  def correct_user
    if @chat.users.include?(current_user)
    else
      redirect_to chats_path, flash: {warning: '您没有权限无法进入此聊天室'}
    end
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_navside.html.erb
<div class="panel with-nav-tabs panel-info">
  <div class="panel-heading">
    <ul class="nav nav-tabs">
      <li class=<%= contact_active %>>
        <a href="#contact-tab" data-toggle="tab"><i class="fa fa-book"></i>通讯录</a>
      </li>
      <li class=<%= chat_active %>>
        <a href="#chat-tab" data-toggle="tab"><i class="fa fa-weixin"></i>聊天</a>
      </li>
    </ul>
  </div>
  <div class="panel-body" id="tab-panel-body">
    <div class="tab-content">
      <div class="tab-pane fade in <%= contact_active %>" id="contact-tab">
        <ul class="list-group">
          <% @friends.each do |user| %>
              <li class="list-group-item" style="padding: 0px; margin-bottom: 0px;">

                <button class="btn btn-default btn-block" data-toggle="collapse" data-target="#user-<%= user.id %>" id="tab-contact-default">
                  <%= image_tag "user-icon.png", class: "img-sm" %>
                  <div class="text-muted">
                    <%= user.name %>
                  </div>
                </button>

                <div id="user-<%= user.id %>" class="collapse">
                  <%= form_for Chat.new, url: chats_path, method: :post do |f| %>
                      <%= hidden_field_tag :users, [user.id] %>
                      <%= button_tag(:class => "btn btn-success btn-block", style: "border-radius: 0;") do %>
                          <i class="fa fa-angle-right"></i> 发起聊天
                      <% end %>
                  <% end %>
                  <%= link_to user_path(user), class: 'btn btn-info btn-block', role: "button", style: "border-radius: 0" do %>
                      <i class="fa fa-angle-right"></i> 用户详情
                  <% end %>
                  <%= link_to friendship_path(user), method: :delete, class: 'btn btn-danger btn-block', role: "button", style: "border-radius: 0;margin:0px;" do %>
                      <i class="fa fa-angle-right"></i> 删除用户
                  <% end %>
                </div>
              </li>
          <% end %>
        </ul>
      </div>

      <div class="tab-pane fade in <%= chat_active %>" id="chat-tab">
        <ul class="list-group">
          <% current_user.chats.each do |chatroom| %>
              <%= link_to chat_path(chatroom), class: 'list-group-item' do %>
                  <i class="fa fa-wechat fa-5"></i> <%= truncate(chatroom.name, length: 10) %>
                  <text id="chatroom-<%= chatroom.id %>"></text>
              <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="panel-footer">
    <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#myModal">添加朋友
    </button>
  </div>
</div>

<%= render "search_fridends" %>

app/views/chats/bot.html.erb
<script type="text/javascript">
  addMsg = function(user, msg) {
    var is_me = user == "我";
    var p_style = is_me ? "color:black;" : "color:green;";
    var li_style = is_me ? "text-align: right;" : "text-align: left;"

    var ul = document.getElementById("list");
    var li = document.createElement("li");
    var p = document.createElement("p");

    li.setAttribute("class", "list-group-item");
    li.setAttribute("style", li_style);
    p.setAttribute("style", p_style);
    p.appendChild(document.createTextNode(msg));
    li.appendChild(p)
    ul.appendChild(li)
  }

updatePerfMetrics = function(averageResponseTime) {
  var li = document.getElementById("averageResponseTime");
  li.innerHTML = `平均响应时间: ${averageResponseTime}ms`;
}

<!-- number of messages sent -->
var numMessage = 0;
<!-- total response time in ms -->
var totalResponseTime;
var sendMsgTime;

callback = function(data, status) {
  <!-- Add response -->
  bot_response = data["response"]
  addMsg("机器人", bot_response);

  <!-- update performance metrics -->
  var date = new Date();
  var elapsedTime = date.getTime() - sendMsgTime;
  if (numMessage == 0) {
    totalResponseTime = elapsedTime
  } else {
    totalResponseTime += elapsedTime
  }

  numMessage++;
  updatePerfMetrics(totalResponseTime / numMessage)
}

sendMsg = function() {
  var input = document.getElementById("input_msg");

  <!-- Add user input message -->
  addMsg("我", input.value)
  url = "http://10.30.6.126:3000/chats/bot_chat";
  post_data = {
    "userId": "<%= current_user.id %>",
    "text": input.value
  }
  jQuery.ajax({
    url: url,
    type: "POST",
    data: JSON.stringify(post_data),
    dataType: "json",
    contentType: "application/json; charset=utf-8",
    success: callback
  })

    <!-- Remember to clear the input -->
  input.value = "";
  var date = new Date();
  sendMsgTime = date.getTime();
}
</script>

<div align="center" class="container">
  <h1>机器人聊天</h1>

  <div class="row">
    <div class="col-sm-6" id="friends_list" align="left" style="max-height:800px; overflow:auto;">
      <ul class="list-group" id="list">
      </ul>
      <form class="form-inline" action="javascript:sendMsg()">
        <input type="text" class="form-control" id="input_msg" style="display:inline;">
        <input type="submit" value="发送" class="btn btn-primary">
      </form>
    </div>

    <div id="performance_window" class="col-sm-5" align="left">
      <ul class="list-group" id="perf">
        <li class="list-group-item" id="userSatisfaction">用户满意度: 100</li>
        <li class="list-group-item" id="numberOnlineUsers">服务用户数: 1</li>
        <li class="list-group-item" id="averageChatTime">平均会话时长: 30min</li>
        <li class="list-group-item" id="averageResponseTime">平均响应时间: 1ns</li>
      </ul>
    </div>
  </div>
</div>

app/views/chats/index.html.erb
<ul class="nav">
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/users/search">添加好友<i class="fas fa-user-plus"></i></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/friendships/requests">未通过<span class="glyphicon glyphicon-ban-circle"></span></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/friendships/grants">待处理<span class="glyphicon glyphicon-list"></span></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/friendships/finished">已处理<span class="glyphicon glyphicon-check"></span></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/chats/bot">机器人聊天<i class="fas fa-robot"></i></a>
  </li>
</ul>

<div class="row">
  <div class="col-sm-4" id="friends_list" style ="max-height:800px; overflow:auto;">
    <ul class="list-group">
      <% @friends.each do |user| %>
      <li class="list-group-item">
        <%= user.name %>

        <%= form_for Chat.new, url: chats_path, method: :post, html: {style: "display: inline;"} do |f| %>
        <%= hidden_field_tag :users, [user.id] %>
        <%= button_tag "发起聊天", class:"btn btn-primary" %>
        <% end %>

        <%= link_to "用户详情", "/user/#{user.id}/public", class:"btn btn-info" %>

        <%= link_to "删除好友", friendship_path(user), method: :delete, class:"btn btn-danger" %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-8">
  </div>
</div>

app/views/chats/show.html.erb
<ul class="nav">
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/users/search">添加好友<i class="fas fa-user-plus"></i></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/friendships/requests">未通过<span class="glyphicon glyphicon-ban-circle"></span></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/friendships/grants">待处理<span class="glyphicon glyphicon-list"></span></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/friendships/finished">已处理<span class="glyphicon glyphicon-check"></span></a>
  </li>
  <li class="nav-item" style="float:left;">
    <a class="nav-link" href="/chats/bot">机器人聊天<i class="fas fa-robot"></i></a>
  </li>
</ul>

<div class="row">
  <div class="col-sm-4" id="friends_list" style ="max-height:800px; overflow:auto;">
    <ul class="list-group">
      <% @friends.each do |user| %>
      <li class="list-group-item">
        <%= user.name %>

        <%= form_for Chat.new, url: chats_path, method: :post, html: {style: "display: inline;"} do |f| %>
        <%= hidden_field_tag :users, [user.id] %>
        <%= button_tag "发起聊天", class:"btn btn-primary" %>
        <% end %>

        <%= link_to "用户详情", "/user/#{user.id}/public", class:"btn btn-info" %>

        <%= link_to "删除好友", friendship_path(user), method: :delete, class:"btn btn-danger" %>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-5">
    <div style ="max-height:800px; overflow:auto;">
      <ul class="list-group">
        <%= sync partial: 'message_row', collection: Message.by_chat(@chat), refetch: true %>
        <%= sync_new partial: 'message_row', resource: Message.new, scope: @chat, refetch: true %>
      </ul>
    </div>
    <div>
      <%= form_for @new_message, remote: true do |f| %>
      <%= f.text_field :body, class: "form-control", style: "width:400px; display: inline;", placeholder: "Type your message here..." %>
      <%= f.submit "发送", class: "btn btn-success" %>
      <%= hidden_field_tag :chat_room, @chat.id %>
      <% end %>
    </div>
  </div>
</div>